# Generated by Django 4.1.1 on 2022-09-12 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
                ('full_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('latitude', models.CharField(max_length=150)),
                ('longitude', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('bucket_list', models.ManyToManyField(related_name='bucket_list_parks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VistedPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_visited_parks', to='nationalparkapi.park')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_parks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='nationalparkapi.park')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('alt_text', models.CharField(max_length=150)),
                ('caption', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=150)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='nationalparkapi.park')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=100)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='nationalparkapi.park')),
            ],
        ),
    ]
