# Generated by Django 4.1.1 on 2022-09-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationalparkapi', '0002_remove_image_alt_text_remove_image_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='park',
            name='full_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='park',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
