# Generated by Django 4.1.1 on 2022-09-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationalparkapi', '0003_alter_park_description_alter_park_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
