# Generated by Django 4.1.1 on 2022-09-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationalparkapi', '0004_alter_image_url_alter_review_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='alt_text',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='credit',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
